CREATE OR REPLACE FUNCTION TOT_PURCH_SF(id IN NUMBER)
RETURN NUMBER IS totalpurch NUMBER;
BEGIN 
SELECT SUM(total) INTO totalpurch FROM BB_BASKET 
WHERE idshopper=id;
RETURN totalpurch;
END;


SELECT idshopper, firstname, lastname, TOT_PURCH_SF(BB_SHOPPER.idshopper) AS TOT_PURCH FROM BB_SHOPPER;

SELECT * FROM BB_SHOPPER;